# Generated by Django 5.2.16 on 2026-07-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('lecteur', 'lecteur'), ('bibliothecaire', 'bibliothecaire'), ('admin', 'admin')], default='lecteur', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
