# Generated by Django 5.2.16 on 2026-07-25 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(verbose_name='Entrer votre âge')),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_created=True)),
                ('titre', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=10, null=True, unique=True)),
                ('date_termine', models.DateTimeField(blank=True, null=True)),
                ('emprunt', models.BooleanField(default=False)),
                ('date_emprunt', models.DateTimeField(blank=True, null=True)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='gestbibliotheque.auteur')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='gestbibliotheque.categorie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
