# Generated by Django 5.2.16 on 2026-07-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestbibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
