# Generated by Django 5.2.16 on 2026-07-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestbibliotheque', '0002_alter_livre_date_ajout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='livre',
            new_name='categorie',
        ),
    ]
